---
- name: update
  hosts: dpisklov-test.dks.lanit.ru
  connection: local
  become: yes

  tasks:

  - name: letter
    raw: echo "Обновлен сертификат SSL" | mail -s "dpisklov-test.dks.lanit.ru" Pisklov@lanit.ru
